name: Reset Database
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Run Database Seed
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: pnpm run seed
